### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/savvie#2]
We need a page and a handler to let users create new accounts. I'll post more details later.

**Comment by ktrinanm** [comment]
Will need both a page and a handler. Write HTML file and something in main.go  (http.HandFunc("/signup",  func ...)) Probably need 2. Signup Page (Name, email,etc)  form method "post", action will be an action URL. Uses r to get the values that the form submitted.

**Comment by ktrinanm** [comment]
I left comments on a few things I need to do for this still. Would you take a look and make sure I'm not forgetting anything?

**Comment by tylermumford** [comment]
If you feel this is done, you can go ahead and close the issue. :smiley:

**Comment by ktrinanm** [comment]
Uh, let me take another look at it tonight and I'll let you know
