### ISSUE TITLE
Resolve/ignore Dezhi's feedback

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/savvie#20]

**Comment by ktrinanm** [comment]
1. Need to have a better logical design on how your pages will be flowing. For example, more generic wording for your UIs would be easier for your users to navigate through your system, such as "decision" and "option" wordings are ambiguous and users need to know what your exact meanings  in your DSS context, and what options are set up for what purpose etc. 

2. Need to have a brief statement to describe what your system is about in your home page, so users will know what to expect to interact with your system. 

3. It would be useful to add anonymous option for voting, as this is truly based on Delphi method. 

4. I also suggest you to come up with a summary page for voting results, so for people who are short of time, they can immediately learn what happened in their voting process. 

5. There is room for UI design improvement, such as adding some relevant graphs and more colors related to your theme would be more appealing to your users.

**Comment by ktrinanm** [comment]
1. Changed "option" to "choice"... I feel more generic is less helpful and doesn't flow quite right. Maybe looking into Delphi will give us an idea of what she wants?  I feel that the flow is more of an issue than the wording......
2. Added a statement. Not very brief, but gives an idea of the site flow
3. Voting is anonymous?
4. Not sure where this would be. Maybe add them on the all-decisions page? For example:
[decision1]    [decision2]    [decision3]
[pie chart      [pie chart       [pie chart
  of voting       of voting       of voting
  for dec.1]      for dec.2]       for dec.3]
Which would also do stuff for 5...
5. I'm thinking we should add some flavor of blue for this. xD
