### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/savvie#5]
We need to decide if we can/should/will keep Nick's C# storage code in the finished product. Part of me thinks it's okay, because we still built the rest of the project. But part of me thinks we should only submit a project if it's entirely our own work.

We should probably just ask Dr. Heiner what she thinks.

**Comment by tylermumford** [comment]
Actually, if we're going to support comments or motions, or anything beyond what it currently supports, then we'll want to rewrite the storage code so it can handle the new data.

**Comment by ktrinanm** [comment]
What do you mean by new data?

**Comment by tylermumford** [comment]
Well, right now we can only store arguments, along with their upvotes and downvotes. If we want to support comments and the whole history of an argument, we'll need a way to store those, too.

**Comment by ktrinanm** [comment]
What design are you imagining? Is a comment basically a subargument that is given a dependency on the original argument?

**Comment by tylermumford** [comment]
No, I'm thinking comments are just simple strings with an associated posting date and the email address of the commenter.

Tyler

**Comment by ktrinanm** [comment]
I think she knows that part of it's Nick's. I told her we even offered to
help Nick with his. I'm not sure though what would be best.

**Comment by tylermumford** [comment]
Great. Then we'll leave Nick's C# code as-is, but we may still need to write new code to store comments; we'll see.

**Comment by tylermumford** [comment]
![image](https://cloud.githubusercontent.com/assets/531333/20917880/4e77b5d0-bb51-11e6-9620-c0887aab0b5f.png)

Basic support for comments added.
