### ISSUE TITLE
Integrate Go templates for page content

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/savvie#6]

**Comment by ktrinanm** [comment]
I want to help with this so I know how it works

**Comment by tylermumford** [comment]
The goal is to use the [html/template](https://golang.org/pkg/html/template/) package to take `.html` files in the `templates` folder and send them to our `w ResponseWriter` objects. That way, we can write the HTML pages in separate files instead of having a bunch of string literals in our source code. 😄

**Comment by ktrinanm** [comment]
Oh that would be nice...

**Comment by tylermumford** [comment]
The `renderTemplate` function means this is done!
