### ISSUE TITLE
Write comments for all Go code

### ISSUE THREAD

**Issue by tylermumford** [tylermumford/savvie#7]
Using the guidelines in https://golang.org/doc/effective_go.html#commentary

- [ ] users.go
- [ ] main.go
- [ ] arguments.go

**Comment by ktrinanm** [comment]
Awesome. I will check that site out. I'm really awful at commenting.....

**Comment by tylermumford** [comment]
Don't worry, it becomes a habit with practice. At least, I hope so!

**Comment by ktrinanm** [comment]
What kind of things do you write? I've read a lot of stuff that says code should be self documenting, but don't Go comments actually make documentation for it?

**Comment by tylermumford** [comment]
Self-documenting code--code so clear and readable that it needs no documentation--is a wonderful ideal, but I think Dr. Heiner wants to see literal comments in our code for this project. Write about why you chose to write a piece of code the way you did, or about how a function is supposed to be used. If you tried something that didn't work, write a comment so future coders don't try it again. And anything you assume about a variable or function should be documented with a comment.  

Tyler
